#!/bin/bash
swappart=sda2
sudo mkswap /dev/"$swappart"
sudo swapon /dev/"$swappart"
sudo bash -c "echo UUID=$(lsblk -no UUID /dev/"$swappart") none swap defaults 0 0 >> /etc/fstab"
HUK="(base udev autodetect modconf block filesystems keyboard keymap resume)"
sed -i "s/^\(HOOKS\s*=\s*\).*\$/\1$HUK/" /etc/mkinitcpio.conf
mkinitcpio -p linux
VAL="\"resume=UUID=$(lsblk -no UUID /dev/"$swappart")\""
sed -i "s/^\(GRUB_CMDLINE_LINUX_DEFAULT\s*=\s*\).*\$/\1$VAL/" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
